export const body: string;
export const button: string;
export const checkboxContainer: string;
export const checkMark: string;
export const checkMarkContainer: string;
export const inputCheckbox: string;
export const inputContainer: string;
export const inputLabel: string;
export const pageContainer: string;
