version: '3'

services:
  client:
    build: '.'
    environment:
      REACT_APP_API_PREFIX: 'http://docker.for.mac.localhost:3001/api'
    ports:
      - '3000:3000'
    networks:
      - 'party-haan'
    volumes:
      - './client:/app'
    depends_on:
      - api
  api:
    build: '.'
    environment:
      PORT: 3001
      POSTGRES_HOST: 'db'
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'party-haan'
      POSTGRES_PASSWORD: 'party-haan'
      POSTGRES_DB: 'party-haan-db'
      SECRET_KEY: 'party-haan-secret-key'
    ports:
      - '3001:3001'
    networks:
      - 'party-haan'
    volumes:
      - './api:/app'
    depends_on:
      - db
  db:
    image: 'postgres:12.4-alpine'
    environment:
      PGDATA: '/var/lib/postgres/data/pgdata'
      POSTGRES_USER: 'party-haan'
      POSTGRES_PASSWORD: 'party-haan'
      POSTGRES_DB: 'party-haan-db'
    ports:
      - '3002:5432'
    networks:
      - 'party-haan'
    volumes:
      - 'db:/var/lib/postgres/data/pgdata'
volumes:
  db:
networks:
  party-haan:
